-- VALEPAC Connect
-- Fix de reconciliación de cartola PortalConcesionario.
-- Ejecutar una sola vez en Supabase antes de desplegar el código.

begin;

alter table public.copec_movimientos
  add column if not exists activo boolean not null default true,
  add column if not exists primera_vez_visto_en timestamptz not null default now(),
  add column if not exists ultima_vez_visto_en timestamptz not null default now(),
  add column if not exists eliminado_portal_en timestamptz null;

create index if not exists copec_movimientos_periodo_activo_idx
  on public.copec_movimientos (periodo, activo, fecha_movimiento);

create index if not exists copec_movimientos_identificador_activo_idx
  on public.copec_movimientos (identificador_origen, activo);

create table if not exists public.copec_movimientos_eliminados_portalconcesionario (
  id bigint generated by default as identity primary key,
  movimiento_id_original text null,
  identificador_origen text not null,
  periodo text null,
  rut_concesionario text null,
  id_eds text null,
  fecha_movimiento date null,
  fecha_contable date null,
  descripcion text null,
  referencia text null,
  tipo_movimiento text null,
  monto numeric null,
  saldo numeric null,
  datos_origen jsonb null,
  primera_vez_visto_en timestamptz null,
  ultima_vez_visto_en timestamptz null,
  eliminado_detectado_en timestamptz not null default now(),
  reactivado_en timestamptz null,
  sincronizacion_id text null,
  motivo text not null default 'ELIMINADO_EN_PORTALCONCESIONARIO'
);

create index if not exists copec_mov_elim_identificador_idx
  on public.copec_movimientos_eliminados_portalconcesionario
  (identificador_origen, eliminado_detectado_en desc);

create index if not exists copec_mov_elim_periodo_idx
  on public.copec_movimientos_eliminados_portalconcesionario
  (periodo, fecha_movimiento);

alter table public.copec_movimientos_eliminados_portalconcesionario enable row level security;

comment on table public.copec_movimientos_eliminados_portalconcesionario is
  'Historial de movimientos que estuvieron en PortalConcesionario y luego dejaron de aparecer en una nueva sincronización.';

comment on column public.copec_movimientos.activo is
  'TRUE si el movimiento sigue presente en la última cartola sincronizada dentro del alcance consultado.';

comment on column public.copec_movimientos.eliminado_portal_en is
  'Fecha en que VALEPAC detectó que PortalConcesionario dejó de informar el movimiento.';

commit;
