-- VALEPAC Connect · M2 margen combustibles
-- Ejecutar una vez en Supabase SQL Editor antes de desplegar el módulo.

create table if not exists public.m2_ventas (
  id bigint generated by default as identity primary key,
  identificador_origen text not null unique,
  fecha date not null,
  codigo_eds text not null default '40098',
  transaccion_id text not null,
  transaccion_codigo text,
  producto_id text,
  producto text not null,
  litros numeric(14,3) not null,
  precio_venta numeric(14,3) not null,
  medio_pago text not null,
  tipo_venta text not null check (tipo_venta in ('ASISTIDA','AUTOSERVICIO')),
  segmento_cliente text not null check (segmento_cliente in ('TAXI_AMIGO','NORMAL')),
  tipo_documento text,
  descripcion_documento text,
  folio text,
  rut_emisor text not null default '78.229.820-8',
  razon_social_emisor text not null default 'VALENCIA Y PACHECO LIMITADA',
  autorizador_fidelidad text,
  datos_origen jsonb,
  sincronizado_en timestamptz not null default now()
);

create index if not exists m2_ventas_fecha_idx on public.m2_ventas(fecha);
create index if not exists m2_ventas_producto_idx on public.m2_ventas(producto);
create index if not exists m2_ventas_tipo_segmento_idx
  on public.m2_ventas(tipo_venta, segmento_cliente);
create index if not exists m2_ventas_medio_pago_idx on public.m2_ventas(medio_pago);

alter table public.m2_ventas enable row level security;

-- El portal usa sus endpoints server-side con service_role. No se habilita
-- lectura/escritura directa desde el navegador.
revoke all on table public.m2_ventas from anon, authenticated;


-- Costo manual BlueMax para M2. Cada registro entra en vigencia desde su fecha.
create table if not exists public.m2_bluemax_costos (
  id bigint generated by default as identity primary key,
  codigo_eds text not null default '40098',
  fecha_vigencia date not null,
  precio_costo numeric(14,3) not null check (precio_costo > 0),
  observacion text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  unique (codigo_eds, fecha_vigencia)
);

create index if not exists m2_bluemax_costos_vigencia_idx
  on public.m2_bluemax_costos(codigo_eds, fecha_vigencia desc);

alter table public.m2_bluemax_costos enable row level security;
revoke all on table public.m2_bluemax_costos from anon, authenticated;
