-- VALEPAC Connect · M2 Lake operacional
-- Ejecutar en el Supabase PRINCIPAL de VALEPAC Connect.
-- Este script NO borra m2_ventas. Primero se crea la nueva estructura y se valida.

begin;

create table if not exists public.m2_resumen_diario (
  fecha date not null,
  producto text not null,
  tipo_venta text not null check (tipo_venta in ('ASISTIDA','AUTOSERVICIO')),
  segmento text not null check (segmento in ('NORMAL','TAXI_AMIGO')),
  litros numeric not null default 0,
  litros_con_costo numeric not null default 0,
  transacciones integer not null default 0,
  m2_neto numeric not null default 0,
  m2_promedio numeric not null default 0,
  actualizado_en timestamptz not null default now(),
  primary key (fecha, producto, tipo_venta, segmento)
);

create index if not exists idx_m2_resumen_fecha
  on public.m2_resumen_diario(fecha);

create table if not exists public.m2_estado_diario (
  fecha date primary key,
  estado text not null default 'PROCESADO' check (estado in ('PROCESADO','ERROR')),
  fuente text not null default 'COPECFUEL_VENTA_COMBUSTIBLE',
  storage_path text,
  sha256 text,
  cantidad_registros integer not null default 0,
  filas_resumen integer not null default 0,
  tamano_json_bytes bigint not null default 0,
  tamano_comprimido_bytes bigint not null default 0,
  ventas_elegibles integer not null default 0,
  ventas_unicas integer not null default 0,
  duplicadas integer not null default 0,
  sin_costo integer not null default 0,
  capturado_en timestamptz,
  procesado_en timestamptz,
  actualizado_en timestamptz not null default now(),
  diagnostico jsonb
);

create index if not exists idx_m2_estado_fecha
  on public.m2_estado_diario(fecha desc);

-- Se conserva el costo manual BlueMax en el Supabase principal.
-- Si esta tabla ya existe por el M2 antiguo, se reutiliza sin borrar sus datos.
create table if not exists public.m2_bluemax_costos (
  id bigint generated by default as identity primary key,
  codigo_eds text not null default '40098',
  fecha_vigencia date not null,
  precio_costo numeric(14,3) not null check (precio_costo > 0),
  observacion text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  unique (codigo_eds, fecha_vigencia)
);

create index if not exists idx_m2_bluemax_costos_vigencia
  on public.m2_bluemax_costos(codigo_eds, fecha_vigencia desc);

-- Costo inicial conocido. No modifica uno existente para la misma fecha.
insert into public.m2_bluemax_costos (codigo_eds, fecha_vigencia, precio_costo)
values ('40098', '2026-10-01', 660.45)
on conflict (codigo_eds, fecha_vigencia) do nothing;

alter table public.m2_resumen_diario enable row level security;
alter table public.m2_estado_diario enable row level security;
alter table public.m2_bluemax_costos enable row level security;

-- El navegador no accede directamente; el portal usa endpoints server-side.
revoke all on table public.m2_resumen_diario from anon, authenticated;
revoke all on table public.m2_estado_diario from anon, authenticated;
revoke all on table public.m2_bluemax_costos from anon, authenticated;

commit;

select
  to_regclass('public.m2_resumen_diario') as m2_resumen_diario,
  to_regclass('public.m2_estado_diario') as m2_estado_diario,
  to_regclass('public.m2_bluemax_costos') as m2_bluemax_costos;
